---
- hosts: all 
  gather_facts: yes
  tasks:
  - name: Distribution
    debug: 
      msg: The OS version of {{ inventory_hostname }} is {{ ansible_distribution }} {{ ansible_distribution_version }}
      #  - name: Distribution version
      #    debug: msg="{{ ansible_distribution_version}}"
      # - name: Distribution major version
      # debug: msg="{{ ansible_distribution_major_version }}"
